version: '3'
services:
  db:
    image: mysql:8.0
    ports:
      - ${MYSQL_PORT}:3306
    container_name: ${PROJECT_NAME}-mysql
    volumes:
      - ./mysql/volumes:/var/lib/mysql
      - ./mysql/:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    env_file: .env

  django_app:
    build:
      context: ./
      dockerfile: ./docker/django/Dockerfile
      args:
        - USER_PASSWORD=${USER_PASSWORD}
    image: ${PROJECT_NAME}
    container_name: ${PROJECT_NAME}-django
    ports:
      - ${DJANGO_PORT}:8000
    volumes:
      - ./apps:/var/www/django
    tty: true
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=db_dev
      - DB_USERNAME=root
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
    command: /bin/bash
    env_file: .env
    depends_on:
      - db