[tool.black]
line-length = 120
target-version = ["py311"]
exclude = '''
(
    migrations
    | develop_tools
)
'''

[tool.isort]
profile = 'black'
line_length = 120
force_single_line = true
force_sort_within_sections = true
lines_after_imports = 2
src_paths = [
  "src"
]
skip_glob = [
  "**/migrations/*",
  "develop_tools/*",
]
