[pytest]
DJANGO_SETTINGS_MODULE = src.config
python_files = tests.py test_*.py *_tests.py

addopts = --reuse-db --ignore=site_media/

filterwarnings =
    ignore::django.utils.deprecation.RemovedInDjango50Warning:
