# Generated by Django 4.2.4 on 2023-08-11 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import src.middleware
import src.utils.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMassage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField(max_length=2048, verbose_name="テキスト")),
                ("created_at", models.DateTimeField(auto_now=True, verbose_name="作成日時")),
                (
                    "created_by",
                    src.utils.models.CurrentUserField(
                        default=src.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="投稿者",
                    ),
                ),
            ],
        ),
    ]
