# Generated by Django 4.2.5 on 2024-02-10 08:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmessage",
            options={"ordering": ["created_at"], "verbose_name": "チャットメッセージ", "verbose_name_plural": "チャットメッセージ"},
        ),
    ]
