name: Django Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: echo ${{ secrets.DOCKER_TOKEN }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin

      - uses: actions/setup-go@v3
        with:
          go-version: 1.21.5
      - run: go run main.go